language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install pycodestyle pylint==1.7.5 pylint-django isort astroid==1.5.3
script:
- sh run_pycodestyle.sh
- sh run_pylint.sh
- sh run_isort.sh
notifications:
  slack:
    secure: XlXO6Tc/hD+NzFWyrzfkLAy1YNTqgSAnO/C5u4tQalM2xeWFwI4kn6OXYetRUpeT9fh7zXvWIzv6zm7y11t0CpC3Cywe3VBaDY4LUHKmsYXGU8wltS7toCqm1V+k/IBvkqx7ibcSuOma6N7UcZyr+z9F1anogzEXYGGp9YneV2W4E4UkzxZXr4lNyQL/HLW262hOcaCotWJpjMyNnv5crvYlxBHqrVCu96htnlK9+/kLTAuRxWU29PndkGrunOv3KWjd966P7OXcJ5CpTgSi8O402TUiWqEUqEVJ+qE2QDFH0IYsW3UzoRtUAzH1nIo5qKTioikgpocUiXwT01hlv1Hjkr+rUoZwm2i7HIYCx022aDl7Z2boNiU8bzJPbkXE24k80S9a1VRlDkCvN2Xt5uyISm6UukPLhlofC6O4nz9QkVcJQucK3J7QBj9QPsygjL0/HN5qVXyqBxHlg2MIw+tWVocxbrFyNkq+xbZ2ttg+sFLl/rcQ33OnV8LpY7sY8PL/avVEBcYiPLODoIEKxBdaXQ6YimMeYnyp7G6P/lQ7TqeSzn4H30obYqXjsB4Jq1tDuX85gvb2e7DYA/4TSVFzqCD8tkETcuOEroJQY1s8ZocuexuU/pAM2z5b+zL+TriO9ARVWlmzuwj3kLT+bX0gnp5OoUYAXKdP+Wi05j4=
    on_success: change

